Database.executeBatch(new AISearchBatchExport('Account', 10000), 200);
Database.executeBatch(new AISearchBatchExport('Opportunity', 10000), 200);
Database.executeBatch(new AISearchBatchExport('Case', 10000), 200);
Database.executeBatch(new AISearchBatchExport('Note', 10000), 200);
Database.executeBatch(new AISearchBatchExport('Property__c', 10000), 200);
Database.executeBatch(new AISearchBatchExport('Lease__c', 10000), 200);
Database.executeBatch(new AISearchBatchExport('Contract__c', 10000), 200);
